### ISSUE TITLE
LIC14 has two print statements

### ISSUE THREAD

**Issue by andreaskth** [sofrel-group14/decide#74]
Since our program is only supposed to output "YES" or "NO", we should remove these println:s.

**Comment by Internet-Person-IP** [comment]
yes you are right, my debugger did not work initially so I did some classic stuff. MB, ill get right to it

**Comment by Internet-Person-IP** [comment]
hello, sorry I think I solved it in another branch so I think if we merge #59 I think we are good to go

**Comment by andreaskth** [comment]
Alright, nice! I'll take a look
